# Generated by Django 4.0.5 on 2022-07-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='Photo',
            field=models.ImageField(upload_to='myimage'),
        ),
    ]
