# Generated by Django 4.0.5 on 2022-07-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_prescription_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='HospitalName',
            field=models.CharField(max_length=100),
        ),
    ]
