# Generated by Django 4.0.5 on 2022-08-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_prescription_hospitalname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
